// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo/demo.proto

package go_micro_srv_demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 托运结果
type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=Consignments,proto3" json:"Consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

// 查看货物信息的请求
// 客户端想要从服务端请求数据，必须有请求格式，哪怕为空
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.demo.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.demo.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.demo.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.demo.GetRequest")
}

func init() { proto.RegisterFile("proto/demo/demo.proto", fileDescriptor_08b73fb6bfa52be9) }

var fileDescriptor_08b73fb6bfa52be9 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x6a, 0xe3, 0x40,
	0x10, 0xc6, 0x4f, 0xfe, 0xaf, 0x91, 0x39, 0xe3, 0x85, 0xbb, 0x13, 0xe7, 0xfc, 0x11, 0xaa, 0x5c,
	0x29, 0xe0, 0xb4, 0x29, 0x42, 0x5c, 0x18, 0x57, 0x81, 0xf5, 0x03, 0x04, 0x47, 0x3b, 0xc8, 0x03,
	0xd1, 0xae, 0xb2, 0xbb, 0x76, 0xde, 0x29, 0x65, 0x8a, 0x3c, 0x5f, 0xd0, 0xca, 0x8a, 0x15, 0x6c,
	0x70, 0x23, 0xf8, 0xe6, 0x9b, 0x6f, 0xe6, 0xa7, 0x91, 0xe0, 0x4f, 0xa1, 0x95, 0x55, 0x37, 0x02,
	0xf3, 0xea, 0x91, 0x38, 0xcd, 0xc6, 0x99, 0x4a, 0x72, 0x4a, 0xb5, 0x4a, 0x8c, 0xde, 0x25, 0xa5,
	0x11, 0x7f, 0x78, 0x10, 0xcc, 0x95, 0x34, 0x94, 0xc9, 0x1c, 0xa5, 0x65, 0xbf, 0xa1, 0x45, 0x22,
	0xf4, 0x22, 0x6f, 0xea, 0xf3, 0x16, 0x09, 0x16, 0x41, 0x20, 0xd0, 0xa4, 0x9a, 0x0a, 0x4b, 0x4a,
	0x86, 0x2d, 0x67, 0x34, 0x4b, 0xec, 0x2f, 0xf4, 0xde, 0x90, 0xb2, 0x8d, 0x0d, 0xdb, 0x91, 0x37,
	0xed, 0xf2, 0xbd, 0x62, 0x77, 0x00, 0xa9, 0x92, 0x76, 0x4d, 0x12, 0xb5, 0x09, 0x3b, 0x51, 0x7b,
	0x1a, 0xcc, 0x2e, 0x92, 0x23, 0x82, 0x64, 0x5e, 0x37, 0xf1, 0x46, 0x3f, 0x9b, 0x80, 0xbf, 0x43,
	0x63, 0xf0, 0xe5, 0x89, 0x44, 0xd8, 0x75, 0x5b, 0x07, 0x55, 0x61, 0x29, 0xe2, 0x1c, 0xfc, 0xef,
	0xd4, 0x11, 0xf1, 0x35, 0x04, 0xe9, 0xd6, 0x58, 0x95, 0xa3, 0x2e, 0xb3, 0x15, 0x31, 0xd4, 0xa5,
	0xa5, 0x28, 0x81, 0x95, 0xa6, 0x8c, 0xa4, 0x03, 0xf6, 0xf9, 0x5e, 0xb1, 0x7f, 0xd0, 0xdf, 0x9a,
	0x2a, 0xd4, 0xa9, 0x8c, 0x52, 0x2e, 0x45, 0xfc, 0xee, 0xc1, 0x80, 0xa3, 0x29, 0x94, 0x34, 0xc8,
	0x42, 0xe8, 0xa7, 0x1a, 0xd7, 0x16, 0xab, 0x9d, 0x03, 0x5e, 0x4b, 0x76, 0x0f, 0x41, 0x7a, 0xb8,
	0xa4, 0x5b, 0x1c, 0xcc, 0xae, 0x4e, 0xbf, 0x71, 0xdd, 0xc5, 0x9b, 0x11, 0xf6, 0x00, 0xc3, 0x86,
	0x67, 0xc2, 0xb6, 0x3b, 0xda, 0xb9, 0x11, 0x3f, 0x32, 0xf1, 0x10, 0x60, 0x81, 0x96, 0xe3, 0xeb,
	0x16, 0x8d, 0x9d, 0x7d, 0x7a, 0x30, 0x5a, 0x6d, 0xa8, 0x28, 0x48, 0x66, 0x2b, 0xd4, 0x3b, 0x4a,
	0x91, 0x71, 0x18, 0xcf, 0x1d, 0x72, 0xf3, 0xbb, 0x9f, 0x59, 0xf2, 0x7f, 0x72, 0xc2, 0xaf, 0x6f,
	0x12, 0xff, 0x62, 0x8f, 0x30, 0x5a, 0xa0, 0x6d, 0x82, 0xb0, 0xcb, 0x13, 0x89, 0x03, 0xd9, 0x99,
	0x81, 0xcf, 0x3d, 0xf7, 0xc7, 0xde, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x79, 0x22, 0x36,
	0xca, 0x02, 0x00, 0x00,
}
