build:
# 一定要注意 makefile 中的缩进，否则 make build 可能报错 Nothing to be done for build
# protoc 命令前边是一个 Tab，不是四个或八个空格
#	protoc -I. --go_out=plugins=grpc:$(GOPATH)/src/demo/demo-service/proto/demo/demo.proto
#	protoc -I. --go_out=plugins=micro:. --micro_out=. proto/demo/demo.proto
	protoc -I. --go_out=plugins=grpc:$(GOPATH)/src/demo/demo-service/proto/demo/demo.proto